defmodule StockDataFetcher.Repo.Migrations.CreateCashflowStatements do
  use Ecto.Migration

  def up do
    create table(:cashflow_statements) do
      add(:stock_id, references(:stocks))
      add(:report_date, :date)
      add(:cash_received_sales, :integer, default: 0)
      add(:net_increase_customer_bank_deposits, :integer, default: 0)
      add(:borrowings_central_bank, :integer, default: 0)
      add(:net_increase_placements_other_financial_institution, :integer, default: 0)
      add(:premiums_received_original_insurance_contract, :integer, default: 0)
      add(:net_cash_received_reinsurance_business, :integer, default: 0)
      add(:net_increase_deposits_policyholder, :integer, default: 0)
      add(:net_increase_disposal_tradable_financial_assets, :integer, default: 0)
      add(:interest_handling_charges_commission_received, :integer, default: 0)
      add(:net_increase_placements_banks, :integer, default: 0)
      add(:net_increase_repurchase_business_capital, :integer, default: 0)
      add(:tax_rebate_received, :integer, default: 0)
      add(:other_cash_received_operating_activities, :integer, default: 0)
      add(:cash_inflows_operating_activities, :integer, default: 0)
      add(:cash_paid_goods_purchased_service_received, :integer, default: 0)
      add(:net_increase_loans_advances_customers, :integer, default: 0)
      add(:net_increase_deposits_with_central_bank_others, :integer, default: 0)
      add(:original_insurance_contract_claims_paid, :integer, default: 0)
      add(:interest_handling_charges_commissions_paid, :integer, default: 0)
      add(:policyholder_dividend_paid, :integer, default: 0)
      add(:cash_paid_employees, :integer, default: 0)
      add(:cash_paid_tax_surcharges, :integer, default: 0)
      add(:cash_paid_other_operating_activities, :integer, default: 0)
      add(:cash_outflows_operating_activities, :integer, default: 0)
      add(:cash_received_disposal_investments, :integer, default: 0)
      add(:investment_income_received, :integer, default: 0)
      add(:net_cash_disposal_fixed_intangible_long_term_assets, :integer, default: 0)
      add(:net_cash_received_disposal_subsidiaries, :integer, default: 0)
      add(:other_cash_received_investing_activities, :integer, default: 0)
      add(:cash_received_decreasing_pledge_time_deposit, :integer, default: 0)
      add(:cash_inflows_investing_activities, :integer, default: 0)
      add(:cash_paid_fixed_intangible_long_term_assets, :integer, default: 0)
      add(:cash_paid_acquisition_investments, :integer, default: 0)
      add(:net_increase_pledge_loans, :integer, default: 0)
      add(:net_cash_paid_acquisition_subsidiaries, :integer, default: 0)
      add(:cash_paid_other_investing_activities, :integer, default: 0)
      add(:cash_paid_increasing_pledge_time_deposit, :integer, default: 0)
      add(:cash_outflows_investing_activities, :integer, default: 0)
      add(:net_cash_flows_investing_activities, :integer, default: 0)
      add(:cash_received_capital_contributions, :integer, default: 0)
      add(:cash_received_cc_by_minority_shareholders_subsidiaries, :integer, default: 0)
      add(:borrowing_received, :integer, default: 0)
      add(:cash_received_bond_issue, :integer, default: 0)
      add(:other_cash_received_financing_activities, :integer, default: 0)
      add(:cash_inflows_financing_activities, :integer, default: 0)
      add(:cash_repayments_amounts_borrowed, :integer, default: 0)
      add(:cash_paid_dividend_profit_distribution_or_interest_payment, :integer, default: 0)
      add(:cash_dividends_profit_minority_shareholders_subsidiaries, :integer, default: 0)
      add(:cash_paid_other_financing_activities, :integer, default: 0)
      add(:cash_outflows_financing_activities, :integer, default: 0)
      add(:net_cash_flows_financing_activities, :integer, default: 0)
      add(:foreign_exchange_rate_fluctuation_on_cash_equivalents, :integer, default: 0)
      add(:beginning_cash_cash_equivalents, :integer, default: 0)
      add(:ending_cash_cash_equivalents, :integer, default: 0)
      add(:net_profit, :integer, default: 0)
      add(:minority_interest_income, :integer, default: 0)
      add(:pending_investment_loss, :integer, default: 0)
      add(:assets_depreciation_reserves, :integer, default: 0)
      add(:depreciation_fixed_oil_productive_biological_assets, :integer, default: 0)
      add(:amortization_intangible_assets, :integer, default: 0)
      add(:long_term_prepaid_expenses, :integer, default: 0)
      add(:decrease_prepaid_expenses, :integer, default: 0)
      add(:increase_withholding_expenses, :integer, default: 0)
      add(:loss_disposal_fixed_intangible_long_term_assets, :integer, default: 0)
      add(:loss_asset_retirement_by_scrapping, :integer, default: 0)
      add(:loss_changes_fair_value, :integer, default: 0)
      add(:increase_deferred_income, :integer, default: 0)
      add(:estimated_liabilities, :integer, default: 0)
      add(:financial_expenses, :integer, default: 0)
      add(:investment_loss, :integer, default: 0)
      add(:decrease_deferred_income_tax_assets, :integer, default: 0)
      add(:increase_deferred_income_tax_liabilities, :integer, default: 0)
      add(:decrease_inventory, :integer, default: 0)
      add(:decrease_operating_receivables, :integer, default: 0)
      add(:increase_operating_payables, :integer, default: 0)
      add(:decrease_cash_receivable_finished_projects, :integer, default: 0)
      add(:increase_cash_advance_unfinished_projects, :integer, default: 0)
      add(:others, :integer, default: 0)
      add(:net_cash_flows_operating_activities, :integer, default: 0)
      add(:conversion_debt_into_capital, :integer, default: 0)
      add(:convertible_bond_due_withone_year, :integer, default: 0)
      add(:fixed_assets_acquired_under_finance_leases, :integer, default: 0)
      add(:ending_balance_cash, :integer, default: 0)
      add(:beginning_balance_cash, :integer, default: 0)
      add(:ending_balance_cash_cash_equivalents, :integer, default: 0)
      add(:beginning_balance_cash_cash_equivalents, :integer, default: 0)
      add(:net_increase_cash_cash_equivalents, :integer, default: 0)
    end

    create(index(:cashflow_statements, [:report_date]))
    create(index(:cashflow_statements, [:stock_id, :report_date], unique: true))
  end

  def down do
    drop(table(:cashflow_statements))
  end
end
