defmodule StockDataFetcher.Repo.Migrations.CreateBalanceSheet do
  use Ecto.Migration

  def up do
    create table(:balance_sheets) do
      add(:stock_id, references(:stocks))
      add(:cash, :integer)
      add(:deposit_reservation, :integer)
      add(:lendings_to_financial_institutions, :integer)
      add(:held_for_trading_financial_assets, :integer)
      add(:financial_derivative, :integer)
      add(:bills_receivables, :integer)
      add(:accounts_receivables, :integer)
      add(:accounts_prepayment, :integer)
      add(:premiums_receivables, :integer)
      add(:reinsurance_premium_receivables, :integer)
      add(:reinsurance_contract_reserve, :integer)
      add(:interest_receivables, :integer)
      add(:dividend_receivables, :integer)
      add(:other_receivables, :integer)
      add(:export_tax_rebate_receivables, :integer)
      add(:allowance_receivables, :integer)
      add(:internal_receivables, :integer)
      add(:buying_back_the_sale_of_financial_assets, :integer)
      add(:inventory, :integer)
      add(:unamortized_expenditures, :integer)
      add(:pending_current_assets_loss, :integer)
      add(:other_current_assests, :integer)
      add(:total_current_assets, :integer)
      add(:loans_and_advances_to_customer, :integer)
      add(:available_for_sale_financial_assets, :integer)
      add(:held_to_maturity_investment, :integer)
      add(:long_term_receivables, :integer)
      add(:long_term_equity_investment, :integer)
      add(:other_long_term_investment, :integer)
      add(:investment_properties, :integer)
      add(:original_value_of_fixed_assets, :integer)
      add(:accumulated_depreciation, :integer)
      add(:net_value_of_fixed_assets, :integer)
      add(:fixed_assets_depreciation_reserves, :integer)
      add(:fixed_assets, :integer)
      add(:construction_in_progress, :integer)
      add(:engineer_material, :integer)
      add(:fixed_assets_in_liquidation, :integer)
      add(:capitalized_biological_assets, :integer)
      add(:non_profit_living_assets, :integer)
      add(:oil_and_gas_assets, :integer)
      add(:intangible_assets, :integer)
      add(:development_expenditure, :integer)
      add(:goodwill, :integer)
      add(:long_term_deferred_expenses, :integer)
      add(:deferred_income_tax_assets, :integer)
      add(:other_long_term_assets, :integer)
      add(:total_long_term_assets, :integer)
      add(:total_assets, :integer)
      add(:short_term_borrowing, :integer)
      add(:borrowing_from_the_central_bank, :integer)
      add(:accept_money_deposits_and_interbank_placement, :integer)
      add(:loans_from_other_banks, :integer)
      add(:transaction_financial_liabilities, :integer)
      add(:derivative_financial_liabilities, :integer)
      add(:bills_payables, :integer)
      add(:accounts_payables, :integer)
      add(:accounts_received_in_advance, :integer)
      add(:financial_assets_solf_for_repruchase, :integer)
      add(:service_fee_payables, :integer)
      add(:payroll_payables, :integer)
      add(:tax_and_dues_payables, :integer)
      add(:interest_payables, :integer)
      add(:dividend_payables, :integer)
      add(:other_levies_payables, :integer)
      add(:other_payables, :integer)
      add(:withholding_expenses, :integer)
      add(:estimated_current_liabilities, :integer)
      add(:the_payable_reinsurance, :integer)
      add(:acting_trading_securities, :integer)
      add(:acting_underwriting_securities, :integer)
      add(:deferred_income, :integer)
      add(:short_term_debentures_payables, :integer)
      add(:long_term_assets_due_within_one_year, :integer)
      add(:other_current_liabilities, :integer)
      add(:total_current_liabilities, :integer)
      add(:long_term_borrowing, :integer)
      add(:bone_payables, :integer)
      add(:long_term_payables, :integer)
      add(:special_payables, :integer)
      add(:estimated_long_term_liabilities, :integer)
      add(:long_term_deferred_income, :integer)
      add(:deferred_income_tax_liabilities, :integer)
      add(:other_long_term_liabilities, :integer)
      add(:total_long_term_liabilities, :integer)
      add(:total_liabilities, :integer)
      add(:actual_receipt_capital, :integer)
      add(:additional_paid_in_capital, :integer)
      add(:treasury_stock, :integer)
      add(:special_reserves, :integer)
      add(:features_surplus, :integer)
      add(:general_risk_preparation, :integer)
      add(:pending_investment_lost, :integer)
      add(:undistributed_profits, :integer)
      add(:proposed_distribution_of_cash_dividends, :integer)
      add(:converted_difference_in_foreign_currency_statements_reserves, :integer)
      add(:parent_company_stockholders_interest, :integer)
      add(:minority_stockholders_interest, :integer)
      add(:owners_equity, :integer)
      add(:total_liabilities_and_equit, :integer)
    end
  end

  def down do
    drop(table(:balance_sheets))
  end
end
